### ISSUE TITLE
Error at package installing

### ISSUE THREAD

**Issue by ShiriNissim** [istornz/live_activities#2]
I started to follow the  setup steps as mentioned in the Readme and after installing this package  tried running it on iPhone 14 Pro Simulator, I'm facing the following issue:

Swift Compiler Error (Xcode): No such module 'ActivityKit'

I have Xcode 14.0.1 version. Can you please guide me on how to solve this issue?

**Comment by istornz** [comment]
Hello !
Thanks for using live_activities
It’s normal because you need to use Xcode 14.1 at least to use activity kit 👍
