### ISSUE TITLE
Live Activities don't shows on Lock Screen and dynamic Island

### ISSUE THREAD

**Issue by bichoalexis** [istornz/live_activities#4]
Hello! 
I have basic knowledge of swift, so I tried to follow step by step the doc. I face that its not enough clear as I except but searching in internet, I could finally create my own widget with the property configuration (or this was that I thought)

- I create a widget following the official documentation (enabling live activities) 
- I create my custom app group following the next documentation: https://developer.apple.com/documentation/xcode/configuring-app-groups
- I set iOS Deployment target to 16.1

But when I tried to use create activity it shows me
XPCErrors] [BSXPCServiceConnectionProxy] Unable to register method "requestActivityWithRequest:error:" on class "BSXPCServiceConnectionProxy<ACActivityInputXPCServer>"
[XPCErrors] [BSXPCServiceConnectionProxy] Unable to register method "endActivityWithIdentifier:payload:options:" on class "BSXPCServiceConnectionProxy<ACActivityInputXPCServer>"
[XPCErrors] [BSXPCServiceConnectionProxy] Unable to register method "updateActivityWithIdentifier:payload:" on class "BSXPCServiceConnectionProxy<ACActivityInputXPCServer>"
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(LIVE_ACTIVITY_ERROR, can't launch live activity, The operation couldn’t be completed. (com.apple.ActivityKit.ActivityInput error 1.), null)

I copy paste your example in my custom app, so Im certainly sure that I miss something...
PD: Im not using URL Scheme because I don't want to share native info to flutter

here is my widgetBundle created in Swift:

`import WidgetKit
import SwiftUI

@main
struct check_in_widgetBundle: WidgetBundle {
    var body: some Widget {
        //check_in_widget()
        if #available(iOS 16.1, *) {
            PizzaDeliveryApp()
        }
    }
}
`

The UI of the widget is the same except by the group name (that I change by my own group name created) and from removing link (where you share native code to flutter)

I have in both (runner target and custom widget Target) the capability of app group
I just have in runner target the capability of push notifications
I have Enable live activities for both your app & widget extension as your readme.

My flutter code is the same as you missing the URL Scheme.

What do Im doing wrong? 
NOTE: I create my widget following the next steps: 

File>New>Target>Widget Extension
I check "include live activity)
I remove the check from "include configuration intent" (because I found that it was not necessary)

When I create the widget it shows me a message for activate scheme
I tried with and without scheme (And without scheme I made it work partially because I couldn't see the live activity and my dynamic island shows loading)

Hope this help

**Comment by bichoalexis** [comment]
My flutter version is 3.3.8
And Im using the latest version of live activities (1.3.0+1)

**Comment by bichoalexis** [comment]
I finally make it work!
Like I said, I recreate my widget again, using your example, when I recreated my widget I change something, I activate the scheme when I was creating my extension, but in this case I forgot to add NSSupportsLiveActivities.

So... I assume that my problem was rejecting the scheme. I suggest you to improve a little bit more the doc, because I face some problems like If it was necessary to change the target version and where did you got your groups xddd (obviously as a beginner of swift). 

Thanks a lot!

**Comment by istornz** [comment]
Thanks for your feedback !

Yeah I'm planning to improve the docs 👍  with some GIFs

Feel free to open a PR if you want 🥇

**Comment by adham-ashraf77** [comment]
> So... I assume that my problem was rejecting the scheme. I suggest you to improve a little bit more the doc, because I fac

what is the scheme please I have a same problem
